⚙️Integrate dotenv
analogue-app/mercury pull request #13
Opened 2020-05-29 22:25 UTC by alihaiderrizvi

Integrated dotenv with the codebase.

2020-05-31 00:34 UTC, hxghhhh commented on apis/artsy.py
> +artsy_api_url = os.getenv("https://api.artsy.net/api")
shouldn't this just be the url?
```suggestions
artsy_api_url = "https://api.artsy.net/api"
```

2020-05-31 00:35 UTC, hxghhhh commented
we should only make the env hold the keys urls we should bake on our side in a constant.py file or just keep it in the code

2020-06-06 16:52 UTC, joelrojo requested changes
@alihaiderrizvi looking good! if you can just get rid of that import (unless we need it). Also can you add the environment keys to this notion doc:
https://www.notion.so/Mercury-API-keys-2bcae4d6433d477d8c5cb89f732afcfe

Similar to the way I did in this notion doc: https://www.notion.so/Mainframe-API-Keys-9c56f75680d64f35ad6b42f8cb1d6a8b

2020-06-06 16:52 UTC, joelrojo commented on utils/enrichment.py
> +import os
@alihaiderrizvi not sure we need this import here?

2020-06-06 17:33 UTC, joelrojo approved these changes

2020-06-06 17:33 UTC, merged