🔥Refactor Wikipedia
analogue-app/mercury pull request #29
Opened 2020-06-20 22:35 UTC by alihaiderrizvi

Changes made:

- Using google search wrapper to land at Wikipedia website for cross-referencing.
- Refactored get_short_details function.

2020-06-21 14:40 UTC, hxghhhh commented on apis/wikipedia.py
> +        return {'message': 'error'}
Have a more specific error message here 
```suggestion
		  return {'message': '[wikipedia] error getting short description'}
```

2020-06-21 14:41 UTC, hxghhhh commented on apis/wikipedia.py
> +    return ''
use `None` here since you are justing doing a basic guard

2020-06-21 14:41 UTC, hxghhhh commented on apis/wikipedia.py
> +    return ''
use `None` here since you are justing doing a basic guard

2020-06-21 14:42 UTC, hxghhhh commented on apis/wikipedia.py
> +    for url in response:
what if there is multiple wikipedia links for a search param? Wouldn't we want to return all of them. In this case we'd only be returning the first one

2020-06-21 14:43 UTC, hxghhhh commented on apis/wikipedia.py
> +    return ''
also write a small test for this

2020-06-21 14:43 UTC, hxghhhh commented on apis/wikipedia.py
> +    return ''
also write a small test for this

2020-06-21 14:44 UTC, hxghhhh requested changes
looks proper, but still needs some work

2020-06-22 16:20 UTC, joelrojo approved these changes
Looking good to me. @alihaiderrizvi assuming you're done with this, safe to merge?

2020-06-22 18:06 UTC, alihaiderrizvi commented
> Looking good to me. @alihaiderrizvi assuming you're done with this, safe to merge?

Yea I'm done with this! Ready for merge 👍

2020-06-22 19:26 UTC, merged